export const cartActionTypes = {
  SET_CART: 'SET_CART',
  SET_CART_INFO: 'SET_CART_INFO',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  REMOVE_ITEM: 'REMOVE_ITEM'
}
